/* pwa.js — generated by pwaify.py.  Registers the service worker, offers an
   install button when the browser says the app is installable, and surfaces a
   quiet "new version" nudge when an updated worker is waiting. */
(function () {
  'use strict';
  if (!('serviceWorker' in navigator)) return;

  var THEME = '#0042AF', FG = '#FDCB40', LABEL = 'Beis Moshiach';
  var standalone = window.matchMedia('(display-mode: standalone)').matches ||
                   window.navigator.standalone === true;

  /* The bottom-right corner is not always ours. A page that already keeps
     something there — an ad badge, a chat launcher — says how much room it
     needs with <meta name="pwa-install-offset" content="66">, and the chip
     sits above it instead of on it. */
  var lift = (function () {
    var m = document.querySelector('meta[name="pwa-install-offset"]');
    var n = m && parseInt(m.content, 10);
    return n > 0 ? n : 16;
  })();

  function chip(text, onClick) {
    var b = document.createElement('button');
    b.type = 'button';
    b.textContent = text;
    b.style.cssText =
      'position:fixed;z-index:2147483000;inset:auto 16px ' + lift + 'px auto;' +
      'font:600 14px/1 system-ui,-apple-system,"Segoe UI",sans-serif;' +
      'padding:11px 16px;border:0;border-radius:999px;cursor:pointer;' +
      'background:' + THEME + ';color:' + FG + ';' +
      'box-shadow:0 6px 20px rgba(0,0,0,.22);opacity:0;transform:translateY(8px);' +
      'transition:opacity .25s ease,transform .25s ease;' +
      'padding-bottom:calc(11px + env(safe-area-inset-bottom,0px))';
    b.addEventListener('click', onClick);
    document.body.appendChild(b);
    requestAnimationFrame(function () { b.style.opacity = '1'; b.style.transform = 'none'; });
    return b;
  }
  function drop(el) {
    if (!el) return;
    el.style.opacity = '0'; el.style.transform = 'translateY(8px)';
    setTimeout(function () { el.remove(); }, 300);
  }

  /* ---- install prompt ------------------------------------------------ */
  var deferred = null, btn = null;
  var DISMISS = 'pwa-install-dismissed';
  var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;

  /* A page can put <meta name="pwa-install-ui" content="custom"> in its head to
     take the install over itself — the corner chip stays out of the way and the
     page drives window.pwaInstall instead. Used where the invitation deserves
     more than a chip. */
  var custom = !!document.querySelector('meta[name="pwa-install-ui"][content="custom"]');

  /* The offer belongs on the way in, not on every page of the site. */
  var landing = /^\/(index\.html)?$/.test(location.pathname);
  /* Asked once. Whatever the answer — installed, declined, or the browser
     prompt closed without a word — it does not come back on this device.
     Private-mode storage throws rather than stores, hence the guards. */
  function forget() { try { localStorage.setItem(DISMISS, '1'); } catch (e) {} }
  var asked = (function () {
    try { return !!localStorage.getItem(DISMISS); } catch (e) { return false; }
  })();

  window.pwaInstall = {
    isIOS: iOS,
    standalone: standalone,
    available: function () { return !!deferred; },
    /* resolves 'accepted' | 'dismissed' | 'unavailable' */
    prompt: function () {
      var d = deferred; deferred = null;
      forget(); asked = true; drop(btn); btn = null;
      if (!d) return Promise.resolve('unavailable');
      d.prompt();
      return d.userChoice.then(function (c) { return c.outcome; });
    },
    onAvailable: function (fn) {
      if (deferred) fn();
      window.addEventListener('pwa-install-available', fn);
    }
  };

  window.addEventListener('beforeinstallprompt', function (e) {
    e.preventDefault();
    deferred = e;
    try { window.dispatchEvent(new Event('pwa-install-available')); } catch (err) {}
    if (custom || !landing) return;
    if (standalone || asked) return;
    if (btn) return;
    btn = chip('Install ' + LABEL, function () {
      forget(); asked = true;          // before the prompt, not after its answer
      drop(btn); btn = null;
      var d = deferred; deferred = null;
      if (d) d.prompt();
    });
  });

  window.addEventListener('appinstalled', function () {
    forget(); asked = true;
    drop(btn); btn = null;
  });

  /* ---- iOS has no beforeinstallprompt: one-time Add-to-Home hint ------ */
  if (iOS && !custom && landing && !standalone && !asked) {
    window.addEventListener('load', function () {
      setTimeout(function () {
        if (btn) return;
        btn = chip('Add ' + LABEL + ' to Home Screen  ⌄', function () {
          forget(); asked = true;
          alert('Tap the Share button in Safari, then choose "Add to Home Screen".');
          drop(btn); btn = null;
        });
      }, 2500);
    });
  }

  /* ---- register + update nudge --------------------------------------- */
  window.addEventListener('load', function () {
    navigator.serviceWorker.register('/sw.js').then(function (reg) {
      function watch(w) {
        if (!w) return;
        w.addEventListener('statechange', function () {
          if (w.state === 'installed' && navigator.serviceWorker.controller) {
            var u = chip('New version — refresh', function () {
              w.postMessage({type: 'SKIP_WAITING'});
              drop(u);
            });
          }
        });
      }
      watch(reg.waiting);
      reg.addEventListener('updatefound', function () { watch(reg.installing); });
    }).catch(function () { /* registration failed: site still works */ });

    var reloading = false;
    navigator.serviceWorker.addEventListener('controllerchange', function () {
      if (reloading) return;
      reloading = true;
      location.reload();
    });
  });
})();
