/* sw.js — generated by pwaify.py.  Do not hand-edit; re-run the tool.
   Strategy: shell + visited pages.
     navigate     -> network first, cache fallback, then /offline.html
     same-origin  -> stale-while-revalidate
     web fonts    -> cache first
     /api/*, /.netlify/*, non-GET, Range -> never touched          */
const VERSION = '2026-08-06-a7cabba2';
const CACHE   = 'app-' + VERSION;
const CORE    = ["/", "/offline.html", "/manifest.webmanifest", "/pwa.js", "/icon-192.png", "/icon-512.png", "/apple-touch-icon.png"];
const NEVER   = [/^\/api\//, /^\/\.netlify\//, /^\/admin\.html$/, /^\/admin-comments\.html$/, /weekly\.json$/];

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // Individually, so one 404 can't abort the whole precache.
    await Promise.all(CORE.map(u => c.add(new Request(u, {cache: 'reload'})).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    if (self.registration.navigationPreload) {
      await self.registration.navigationPreload.enable().catch(() => {});
    }
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith('app-') && k !== CACHE)
                          .map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', e => {
  if (e.data && e.data.type === 'SKIP_WAITING') self.skipWaiting();
});

const isFont = u => u.hostname === 'fonts.gstatic.com' || u.hostname === 'fonts.googleapis.com';

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET' || req.headers.has('range')) return;

  const url = new URL(req.url);

  if (url.origin === self.location.origin) {
    if (NEVER.some(rx => rx.test(url.pathname))) return;
  } else if (!isFont(url)) {
    return;                                    // other cross-origin: leave alone
  }

  if (req.mode === 'navigate') {
    event.respondWith(navigateFirst(event));
    return;
  }
  event.respondWith(isFont(url) ? cacheFirst(req) : staleWhileRevalidate(req));
});

async function navigateFirst(event) {
  const req = event.request;
  const cache = await caches.open(CACHE);
  try {
    const preload = await event.preloadResponse;
    const res = preload || await fetch(req);
    if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
    return res;
  } catch (_) {
    return (await cache.match(req, {ignoreSearch: true}))
        || (await cache.match('/offline.html'))
        || new Response('Offline', {status: 503, headers: {'content-type': 'text/plain'}});
  }
}

async function staleWhileRevalidate(req) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(req);
  const net = fetch(req).then(res => {
    if (res && res.ok && (res.type === 'basic' || res.type === 'cors')) {
      cache.put(req, res.clone());
    }
    return res;
  }).catch(() => null);
  return hit || (await net) || new Response('', {status: 504});
}

async function cacheFirst(req) {
  const cache = await caches.open(CACHE);
  const hit = await cache.match(req);
  if (hit) return hit;
  try {
    const res = await fetch(req);
    if (res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone());
    return res;
  } catch (_) {
    return new Response('', {status: 504});
  }
}
